### ISSUE TITLE
Unable to start wsa (open file management or developer options from the settings interface), it will close automatically

### ISSUE THREAD

**Issue by Doddddd** [LSPosed/MagiskOnWSA#189]
same as #102 , I tried the file provided in it, but I still couldn't start it.

**Comment by Doddddd** [comment]
[25012022015245.log](https://github.com/LSPosed/MagiskOnWSA/files/7927850/25012022015245.log)

**Comment by yujincheng08** [comment]
```
01-24 17:52:52.159   221   490 E WindowManager: Window Session Crash

01-24 17:52:52.159   221   490 E WindowManager: java.lang.IllegalArgumentException: Requested window null does not exist

01-24 17:52:52.159   221   490 E WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:5443)

01-24 17:52:52.159   221   490 E WindowManager: 	at com.android.server.wm.Session.actionOnWallpaper(Session.java:356)

01-24 17:52:52.159   221   490 E WindowManager: 	at com.android.server.wm.Session.setWallpaperZoomOut(Session.java:382)

01-24 17:52:52.159   221   490 E WindowManager: 	at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:1154)

01-24 17:52:52.159   221   490 E WindowManager: 	at com.android.server.wm.Session.onTransact(Session.java:139)

01-24 17:52:52.159   221   490 E WindowManager: 	at android.os.Binder.execTransactInternal(Binder.java:1159)

01-24 17:52:52.159   221   490 E WindowManager: 	at android.os.Binder.execTransact(Binder.java:1123)
```

Looks like a crash from WSA itself and not a problem of ours.
