### ISSUE TITLE
Workflow will not add magisk

### ISSUE THREAD

**Issue by andythegreat87** [LSPosed/MagiskOnWSA#273]
It's been causing it to fail 

I get:
Run import requests
**__d**_ownloading link: https://downloads.sourceforge.net/project/opengapps/x86_64/20220215/open_gapps-x86_64-11.0-pico-20220215.zip
Traceback (most recent call last):
  File "/home/runner/work/_temp/8631d355-f6e1-4187-8d1e-a7b0d[30](https://github.com/andythegreat87/MagiskOnWSA/runs/5685374599?check_suite_focus=true#step:5:30)66c16.py", line 22, in <module>
    urllib.request.urlretrieve(link, out_file)
  File "/usr/lib/python3.8/urllib/request.py", line 276, in urlretrieve
    block = fp.read(bs)
  File "/usr/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 12[41](https://github.com/andythegreat87/MagiskOnWSA/runs/5685374599?check_suite_focus=true#step:5:41), in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
Error: The operation was canceled.__**_**

When I run the workflow, I am not  canceling it and it once would not add Magisk

**Comment by yujincheng08** [comment]
Because the other build matrix failed.
