### ISSUE TITLE
play store crashes when youtube app installed

### ISSUE THREAD

**Issue by njsnowboarder** [LSPosed/MagiskOnWSA#313]
Hi!  I attached a log here.  When i install youtube app from play store,  subsequently  _play store crashes after 1-2 seconds_ cant use play store anymore.  If i uninstall youtube app, play store runs normally again.  Seems kind of odd youtube app runs fine, but installing it crashes the Play store app.

[Log_2022-04-19_11-00-19.txt](https://github.com/LSPosed/MagiskOnWSA/files/8514193/Log_2022-04-19_11-00-19.txt)
.

**Comment by yujincheng08** [comment]
play store will invoke to play promotion video and this is not supported by WSA.

```

04-18 19:16:03.113  4410  4427 E AndroidRuntime: Process: com.google.android.youtube.player, PID: 4410

04-18 19:16:03.113  4410  4427 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@7213c93 is not valid; is your activity running?

04-18 19:16:03.113  4410  4427 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1071)

04-18 19:16:03.113  4410  4427 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)

04-18 19:16:03.113  4410  4427 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)

04-18 19:16:03.113  4410  4427 E AndroidRuntime: 	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1576)

04-18 19:16:03.113  4410  4427 E AndroidRuntime: 	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1342)

04-18 19:16:03.113  4410  4427 E AndroidRuntime: 	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1308)
```

I think it's WSA's problem because Microsoft has drastically changed how app displays. Please ask Microsoft for further help.
