### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by vignakke** [LSPosed/MagiskOnWSA#382]
Download OpenGApps:

Run import requests
downloading link: https://downloads.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-nano-20220503.zip
Traceback (most recent call last):
  File "/home/runner/work/_temp/9e00ffe4-7b5f-4559-8ccb-d976a0d4b544.py", line 30, in <module>
    urllib.request.urlretrieve(link, out_file)
  File "/usr/lib/python3.8/urllib/request.py", line 276, in urlretrieve
    block = fp.read(bs)
  File "/usr/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 12[41](https://github.com/vignakke/MagiskOnWSA-1/runs/6618579906?check_suite_focus=true#step:5:42), in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
Error: Process completed with exit code 1.

**Comment by Howard20181** [comment]
Network error, try again.
