### ISSUE TITLE
Download WSA part of workflow keeps failing with connection refused (ssl failure?), exit code 1

### ISSUE THREAD

**Issue by QuinTeknoLife** [LSPosed/MagiskOnWSA#473]
When I try to execute the workflow (x64, fast ring, canary magisk, pico gApps, remove Amazon, root magisk) I keep on running into this error during the 'Download WSA' job of the workflow. I am perfectly able to download the .msixbundle when using the website but for some strange reason it fails in the job.

`Run import requests
  [..]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f2a9f8c1130>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='store.rg-adguard.net', port=443): Max retries exceeded with url: /api/GetFiles (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2a9f8c1130>: Failed to establish a new connection: [Errno 111] Connection refused'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/runner/work/_temp/da87a1ce-7369-4983-b84d-337c5e9b03d5.py", line 12, in <module>
    res = requests.post("https://store.rg-adguard.net/api/GetFiles", f"type=CategoryId&url=85[80](https://github.com/QuinTeknoLife/MagiskOnWSA/runs/7426173929?check_suite_focus=true#step:3:81)14f3-3[93](https://github.com/QuinTeknoLife/MagiskOnWSA/runs/7426173929?check_suite_focus=true#step:3:94)4-4abe-8078-4aa193e74ca8&ring={release_type}&lang=en-US", headers={
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='store.rg-adguard.net', port=443): Max retries exceeded with url: /api/GetFiles (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2a9f8c1130>: Failed to establish a new connection: [Errno [111](https://github.com/QuinTeknoLife/MagiskOnWSA/runs/7426173929?check_suite_focus=true#step:3:112)] Connection refused'))
Error: Process completed with exit code 1.`

**Comment by Howard20181** [comment]
It's not a problem we can solve.
Try again

**Comment by QuinTeknoLife** [comment]
Still keeps failing. Does the download have to be through an SSL connection? When HTTPS fails normally I would try HTTP/port 80 as an alternative to see if that does work but I have no clue if that even is a posibility with the current code. (My python is errr... lacking, I'm more familiar in other languages :P)

**Comment by QuinTeknoLife** [comment]
> It's not a problem we can solve. Try again

Still keeps failing. Does the download have to be through an SSL connection? When HTTPS fails normally I would try HTTP/port 80 as an alternative to see if that does work but I have no clue if that even is a posibility with the current code. (My python is errr... lacking, I'm more familiar in other languages :P)

**Comment by RyouFuchiKyou** [comment]
So are we just supposed to keep running it??

**Comment by applepear19** [comment]
its now working.

**Comment by yujincheng08** [comment]
Fixed by #481
